name: ${selectedProjectName}-redis

services:
  # This is your local Redis database instance
  redis-db:
    image: redis:8
    restart: always
    volumes:
      - ${selectedProjectName}-data:/data
    ports:
      - "127.0.0.1:6969:6379" # Access the Redis DB at port 6969

  # Use RedisInsight to view and manage Redis at localhost:8069
  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "127.0.0.1:8069:5540"

volumes:
  ${selectedProjectName}-data:
    driver: local
